// <auto-generated />
using System;
using AdvertAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200611182108_SeedBannerDb")]
    partial class SeedBannerDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertAPI.Models.Banner", b =>
                {
                    b.Property<int>("IdAdvertisement")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal");

                    b.Property<int>("IdCampaign")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.HasKey("IdAdvertisement")
                        .HasName("Banner_pk");

                    b.HasIndex("IdCampaign");

                    b.ToTable("Banner","apbd_project");

                    b.HasData(
                        new
                        {
                            IdAdvertisement = 1,
                            Area = 7m,
                            IdCampaign = 1,
                            Name = "Name_1",
                            Price = 600m
                        },
                        new
                        {
                            IdAdvertisement = 2,
                            Area = 4m,
                            IdCampaign = 2,
                            Name = "Name_2",
                            Price = 300m
                        },
                        new
                        {
                            IdAdvertisement = 3,
                            Area = 5m,
                            IdCampaign = 4,
                            Name = "Name_3",
                            Price = 500m
                        },
                        new
                        {
                            IdAdvertisement = 4,
                            Area = 3m,
                            IdCampaign = 3,
                            Name = "Name_4",
                            Price = 360m
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Building", b =>
                {
                    b.Property<int>("IdBuilding")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("IdBuilding")
                        .HasName("Building_pk");

                    b.ToTable("Building","apbd_project");

                    b.HasData(
                        new
                        {
                            IdBuilding = 1,
                            City = "Manhattan",
                            Height = 54.6m,
                            Street = "Wall",
                            StreetNumber = 33
                        },
                        new
                        {
                            IdBuilding = 2,
                            City = "Manhattan",
                            Height = 54.6m,
                            Street = "Wall",
                            StreetNumber = 34
                        },
                        new
                        {
                            IdBuilding = 3,
                            City = "Manhattan",
                            Height = 15.44m,
                            Street = "Astor Place",
                            StreetNumber = 1
                        },
                        new
                        {
                            IdBuilding = 4,
                            City = "Manhattan",
                            Height = 15.44m,
                            Street = "Astor Place",
                            StreetNumber = 3
                        },
                        new
                        {
                            IdBuilding = 5,
                            City = "Manhattan",
                            Height = 100.4m,
                            Street = "Bleecker",
                            StreetNumber = 68
                        },
                        new
                        {
                            IdBuilding = 6,
                            City = "Manhattan",
                            Height = 100.4m,
                            Street = "Bleecker",
                            StreetNumber = 69
                        },
                        new
                        {
                            IdBuilding = 7,
                            City = "Brooklyn",
                            Height = 28.5m,
                            Street = "Flatbush Ave",
                            StreetNumber = 80
                        },
                        new
                        {
                            IdBuilding = 8,
                            City = "Brooklyn",
                            Height = 28.5m,
                            Street = "Flatbush Ave",
                            StreetNumber = 81
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Campaign", b =>
                {
                    b.Property<int>("IdCampaign")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FromIdBuilding")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("ToIdBuilding")
                        .HasColumnType("int");

                    b.HasKey("IdCampaign")
                        .HasName("Campaign_pk");

                    b.HasIndex("FromIdBuilding");

                    b.HasIndex("IdClient");

                    b.HasIndex("ToIdBuilding");

                    b.ToTable("Campaign","apbd_project");

                    b.HasData(
                        new
                        {
                            IdCampaign = 1,
                            EndDate = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 1,
                            IdClient = 1,
                            PricePerSquareMeter = 120m,
                            StartDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 2
                        },
                        new
                        {
                            IdCampaign = 2,
                            EndDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 3,
                            IdClient = 2,
                            PricePerSquareMeter = 200m,
                            StartDate = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 4
                        },
                        new
                        {
                            IdCampaign = 3,
                            EndDate = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 5,
                            IdClient = 3,
                            PricePerSquareMeter = 170m,
                            StartDate = new DateTime(2020, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 6
                        },
                        new
                        {
                            IdCampaign = 4,
                            EndDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 7,
                            IdClient = 2,
                            PricePerSquareMeter = 160m,
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 8
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("IdClient")
                        .HasName("Client_pk");

                    b.ToTable("Client","apbd_project");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Email = "jon@doe.com",
                            FirstName = "Jon",
                            LastName = "Doe",
                            Login = "jondoe",
                            Password = "DR6UFyuKs8ybA9UUb4dF4h2tqf+u2uWExaKl7HTbhgXvUFOvwfHt4Cpbzv8tTohMI6uMSTddyYjYv2MugeOSjc0Y3zr8Z1ujSOAn3b+wjzzWUIzTaAmQ4tzBvPmotqrFoeuE/w+FLu9m2H3xLTPgGpsyrtPr9Nl9mqgrILnvvLsWBybDBDzH//SBiqUFMRuI0SIdZO/jbO4m425HRGBEg8r7+CslFdxKcMGNEerTB3wXu1dTLmSEPV6ieIJPhqtfoKqo/0wmP6Cf344atD5MZfa7E2zl3JafX+DwsgdcYfeV0y34sTsBW5WaJLSmpSLNuS0wbXHBk82PefQKyZPN1A==",
                            Phone = "66666666"
                        },
                        new
                        {
                            IdClient = 2,
                            Email = "michal@scott.com",
                            FirstName = "Michal",
                            LastName = "Scott",
                            Login = "dunder_mifflin",
                            Password = "UigqOl6oPqUlZFUqSvgS/gWNeY85VBlOH6hl/t7O1mKK4jr8/sH2Ojbo4LS05EnL4iReoMIlbMsQsSvmUnpoDpOSWsvCuBSqfs5LqRBk88MigvgOXIwvtM+GyZ/N5FT09JhJOLKyLROGk0yfOq5wPSdsMOzEAOBPw6qo+eJumDXkVCRZYQsanLlnlPYa6ANM//vIfMgXRmV2N2kbYOjDdVRJJpNaF+AStci0nDWTwdGlT001H7I6K+T/2zA6DcZjL55YiIVYtsz5IvNNTvyUoojC/PtCe4DibW2dOrFr+EoMtIj+3IF9kwWPC7sGcS1CR8jq6bBOaORcHzBAqp3J+A==",
                            Phone = "5720935"
                        },
                        new
                        {
                            IdClient = 3,
                            Email = "Jack@Daniels.com",
                            FirstName = "Jack",
                            LastName = "Daniels",
                            Login = "bourbon",
                            Password = "jvd+Zfkkw2XJE/5/sCstVjiWgKyXXotW4OkUtiI9pJ+2h1p/qLIVPRldkfG1JF4nISLmQ7MDaRoMudmsWGN9NfBJiFw0qjaSjlBFAeWpVJVw7UFckJ7Pkqmqn53S2AqnmAJctF2Hq1EGYmvhzwo8Ii2XQOk1unkeXWh5wEsW/ulevPRDIxp6l1kfQB//LiubwS141ddGuwLMLweIZhPfAkDfb3fuNl4pNDT74N5K/OPRdCSFqGPpDSCns02A8G+dWHNt51vzEW8pA8lyEh/QgDhMmP4q/FsKFgEZ3SaLz4T/5GQJvYXKHjo6/vc5nmdSNCG6WbdtxMHutFj0vB0euA==",
                            Phone = "1234567878"
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Banner", b =>
                {
                    b.HasOne("AdvertAPI.Models.Campaign", "Campaign")
                        .WithMany("Banner")
                        .HasForeignKey("IdCampaign")
                        .HasConstraintName("Campaign_Banner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvertAPI.Models.Campaign", b =>
                {
                    b.HasOne("AdvertAPI.Models.Building", "FromBuilding")
                        .WithMany("CampaignFrom")
                        .HasForeignKey("FromIdBuilding")
                        .HasConstraintName("FromBuilding_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AdvertAPI.Models.Client", "Client")
                        .WithMany("Campaign")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("Client_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AdvertAPI.Models.Building", "ToBuilding")
                        .WithMany("CampaignTo")
                        .HasForeignKey("ToIdBuilding")
                        .HasConstraintName("ToBuilding_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
