// <auto-generated />
using System;
using AdvertAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200611182002_SeedBuildingDb")]
    partial class SeedBuildingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertAPI.Models.Banner", b =>
                {
                    b.Property<int>("IdAdvertisement")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal");

                    b.Property<int>("IdCampaign")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.HasKey("IdAdvertisement")
                        .HasName("Banner_pk");

                    b.HasIndex("IdCampaign");

                    b.ToTable("Banner","apbd_project");
                });

            modelBuilder.Entity("AdvertAPI.Models.Building", b =>
                {
                    b.Property<int>("IdBuilding")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("IdBuilding")
                        .HasName("Building_pk");

                    b.ToTable("Building","apbd_project");

                    b.HasData(
                        new
                        {
                            IdBuilding = 1,
                            City = "Manhattan",
                            Height = 54.6m,
                            Street = "Wall",
                            StreetNumber = 33
                        },
                        new
                        {
                            IdBuilding = 2,
                            City = "Manhattan",
                            Height = 54.6m,
                            Street = "Wall",
                            StreetNumber = 34
                        },
                        new
                        {
                            IdBuilding = 3,
                            City = "Manhattan",
                            Height = 15.44m,
                            Street = "Astor Place",
                            StreetNumber = 1
                        },
                        new
                        {
                            IdBuilding = 4,
                            City = "Manhattan",
                            Height = 15.44m,
                            Street = "Astor Place",
                            StreetNumber = 3
                        },
                        new
                        {
                            IdBuilding = 5,
                            City = "Manhattan",
                            Height = 100.4m,
                            Street = "Bleecker",
                            StreetNumber = 68
                        },
                        new
                        {
                            IdBuilding = 6,
                            City = "Manhattan",
                            Height = 100.4m,
                            Street = "Bleecker",
                            StreetNumber = 69
                        },
                        new
                        {
                            IdBuilding = 7,
                            City = "Brooklyn",
                            Height = 28.5m,
                            Street = "Flatbush Ave",
                            StreetNumber = 80
                        },
                        new
                        {
                            IdBuilding = 8,
                            City = "Brooklyn",
                            Height = 28.5m,
                            Street = "Flatbush Ave",
                            StreetNumber = 81
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Campaign", b =>
                {
                    b.Property<int>("IdCampaign")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FromIdBuilding")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("ToIdBuilding")
                        .HasColumnType("int");

                    b.HasKey("IdCampaign")
                        .HasName("Campaign_pk");

                    b.HasIndex("FromIdBuilding");

                    b.HasIndex("IdClient");

                    b.HasIndex("ToIdBuilding");

                    b.ToTable("Campaign","apbd_project");
                });

            modelBuilder.Entity("AdvertAPI.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("IdClient")
                        .HasName("Client_pk");

                    b.ToTable("Client","apbd_project");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Email = "jon@doe.com",
                            FirstName = "Jon",
                            LastName = "Doe",
                            Login = "jondoe",
                            Password = "weiIi7CX75r7W29pKEiNm6gcq++mpv6YJWHjSEDvN8Nm2FWPZg3/UzZ+n00vJosEqwrkgxlfyzrwW12KfZHQRBo5kmjiBjoyXBGbwm0B3wfg6vaYQPsiKX8DTsLFl/uuOnqz6oxDXpxN/LqIVv9XJQKh99TyrYRJXkA1dvnLLkEvsXqAX+QHRTjGJaI2Vaxso3VZFyz+kHarqM7NPkAF5r5njPsFzub1qmVIGZB5T28LzaKtJLoNI/aZ3eOyU6op0t408Ymyang4AzIOVUc21UkLAuTyhumx3kToqY46v8knFDRVfMpJeOiR/UF3gSEBZjUZLmiFXsm0awsifcpY1g==",
                            Phone = "66666666"
                        },
                        new
                        {
                            IdClient = 2,
                            Email = "michal@scott.com",
                            FirstName = "Michal",
                            LastName = "Scott",
                            Login = "dunder_mifflin",
                            Password = "gS4JDVLRzf1L58n35pHNggFpYvihkXGgDS25Hth7N2e7peKvpcAvHBq8tg6zFvvtEb3Vmp+euc8MXTBNy3fh8D7ZYODYGBNtrb6K7RlPDvWYGGaiqH4Al8rEZnM7icqzkgCagvOE142MdY0DlmVfaavcQlof1k3ixOGbCpRr/ixm0rkL+D3Ej3b7zVY5O0AcrMLOH4u3laqOVa4Ritoigfy7Awu0DtvDxp70EcvVfYcv5/wZUTXGwoTFJPRqOvm3fR1Sy4EhKAYF3Kqkr5NgI84Tb2uP5JVJ3b1LFwQTQ5Xdxd8/FPNXlCIOwGqkHqj2EXcMVlO32fHhTpP7BDnpGQ==",
                            Phone = "5720935"
                        },
                        new
                        {
                            IdClient = 3,
                            Email = "Jack@Daniels.com",
                            FirstName = "Jack",
                            LastName = "Daniels",
                            Login = "bourbon",
                            Password = "LHt/u342UFasHQsmauomJKA073IZ+fwbPOEADARc1airImbmTa6l/kPbRvCiKVcLox2HsxOlUJv/ciVd5dGo5qNrQVSDuFOLOeEbrcOGbEqu2Be4V1ZG/nl/LpeuCXcyHklSvho0B3SAQdDZbokz2yi8D6YZPzlnZ9oupUSsbcT6cIY1Y4CQMTK+EEFcbfDbI3x8FvcXKSkCNSkMqOO4QU9ISyrMGkeAYdwl1itmzSN0/JPRrdTF8pycdM1k2PUtDSM2vgt5WXh4CAz3cIEfA/CzhMeWZ4skZZLoIn+DUjD6sQY4uBbeynReS6XprKIDaJYjn2rU3ddPVZGR0iQVTg==",
                            Phone = "1234567878"
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Banner", b =>
                {
                    b.HasOne("AdvertAPI.Models.Campaign", "Campaign")
                        .WithMany("Banner")
                        .HasForeignKey("IdCampaign")
                        .HasConstraintName("Campaign_Banner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvertAPI.Models.Campaign", b =>
                {
                    b.HasOne("AdvertAPI.Models.Building", "FromBuilding")
                        .WithMany("CampaignFrom")
                        .HasForeignKey("FromIdBuilding")
                        .HasConstraintName("FromBuilding_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AdvertAPI.Models.Client", "Client")
                        .WithMany("Campaign")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("Client_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AdvertAPI.Models.Building", "ToBuilding")
                        .WithMany("CampaignTo")
                        .HasForeignKey("ToIdBuilding")
                        .HasConstraintName("ToBuilding_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
