// <auto-generated />
using System;
using AdvertAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200611182034_SeedCampaignDb")]
    partial class SeedCampaignDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertAPI.Models.Banner", b =>
                {
                    b.Property<int>("IdAdvertisement")
                        .HasColumnType("int");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal");

                    b.Property<int>("IdCampaign")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.HasKey("IdAdvertisement")
                        .HasName("Banner_pk");

                    b.HasIndex("IdCampaign");

                    b.ToTable("Banner","apbd_project");
                });

            modelBuilder.Entity("AdvertAPI.Models.Building", b =>
                {
                    b.Property<int>("IdBuilding")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("IdBuilding")
                        .HasName("Building_pk");

                    b.ToTable("Building","apbd_project");

                    b.HasData(
                        new
                        {
                            IdBuilding = 1,
                            City = "Manhattan",
                            Height = 54.6m,
                            Street = "Wall",
                            StreetNumber = 33
                        },
                        new
                        {
                            IdBuilding = 2,
                            City = "Manhattan",
                            Height = 54.6m,
                            Street = "Wall",
                            StreetNumber = 34
                        },
                        new
                        {
                            IdBuilding = 3,
                            City = "Manhattan",
                            Height = 15.44m,
                            Street = "Astor Place",
                            StreetNumber = 1
                        },
                        new
                        {
                            IdBuilding = 4,
                            City = "Manhattan",
                            Height = 15.44m,
                            Street = "Astor Place",
                            StreetNumber = 3
                        },
                        new
                        {
                            IdBuilding = 5,
                            City = "Manhattan",
                            Height = 100.4m,
                            Street = "Bleecker",
                            StreetNumber = 68
                        },
                        new
                        {
                            IdBuilding = 6,
                            City = "Manhattan",
                            Height = 100.4m,
                            Street = "Bleecker",
                            StreetNumber = 69
                        },
                        new
                        {
                            IdBuilding = 7,
                            City = "Brooklyn",
                            Height = 28.5m,
                            Street = "Flatbush Ave",
                            StreetNumber = 80
                        },
                        new
                        {
                            IdBuilding = 8,
                            City = "Brooklyn",
                            Height = 28.5m,
                            Street = "Flatbush Ave",
                            StreetNumber = 81
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Campaign", b =>
                {
                    b.Property<int>("IdCampaign")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FromIdBuilding")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("ToIdBuilding")
                        .HasColumnType("int");

                    b.HasKey("IdCampaign")
                        .HasName("Campaign_pk");

                    b.HasIndex("FromIdBuilding");

                    b.HasIndex("IdClient");

                    b.HasIndex("ToIdBuilding");

                    b.ToTable("Campaign","apbd_project");

                    b.HasData(
                        new
                        {
                            IdCampaign = 1,
                            EndDate = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 1,
                            IdClient = 1,
                            PricePerSquareMeter = 120m,
                            StartDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 2
                        },
                        new
                        {
                            IdCampaign = 2,
                            EndDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 3,
                            IdClient = 2,
                            PricePerSquareMeter = 200m,
                            StartDate = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 4
                        },
                        new
                        {
                            IdCampaign = 3,
                            EndDate = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 5,
                            IdClient = 3,
                            PricePerSquareMeter = 170m,
                            StartDate = new DateTime(2020, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 6
                        },
                        new
                        {
                            IdCampaign = 4,
                            EndDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromIdBuilding = 7,
                            IdClient = 2,
                            PricePerSquareMeter = 160m,
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToIdBuilding = 8
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("IdClient")
                        .HasName("Client_pk");

                    b.ToTable("Client","apbd_project");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Email = "jon@doe.com",
                            FirstName = "Jon",
                            LastName = "Doe",
                            Login = "jondoe",
                            Password = "RRgXFZLyFhlyMUpyJPDWjVlzn6mnF4fh4xqpAuHsBpV+weSaVPZkFPpBndQjX9XZZnUnbkhFcb0BrtfWTj7GLtIB78u81YZkEeKwoyQN736zhLiftS+XSRyeJqzN5h4swEOvSNkGbeHa4LcpTpXTJVi/mJPY/jjQOFjEReFCf7xvokqplw7qhFJU7Fi0SoO9lH+/Z3acjdwsTj604u16pr7doeKsrYio9EZyRyT5LkOKZPikxVg4Qh7uTw6FqvoovkaKVVvOCWHBHxe3d/I3zykIUx6wnYYhwc1alYQMyAS6BYD68a7K3dd1XCw42P/IeRt34yerAs6MxbwwHxTYwg==",
                            Phone = "66666666"
                        },
                        new
                        {
                            IdClient = 2,
                            Email = "michal@scott.com",
                            FirstName = "Michal",
                            LastName = "Scott",
                            Login = "dunder_mifflin",
                            Password = "zT6+ffSnc0Znyr1SVCM5HqBHmFYTx4ys5MY6RBNkhSKM4cf8upZnj4XLzLsSNEb5lIm+L7Z/RDrHwl2NmwrMnASDACoT0GSr8UWol/s+OLEPxNkpOiyKSBYhy24G8Dc3OG0PS/3CP+7IVunL0RK6iVQBLoWuQU4jS0FWfyn+j70FS0ECcyWYMj0c13VBpH4ntOtfKMiNVAXHA0voWblshgqdLHNEfCJfVIqvo4UmtlPlSJ17hWHd7cwgM5QtDInCKOBlh/9PzHNmPCkFvH6z9O87P1U+BWX8+LhaKRqvyMXYpLr7K0hXWA8vWVJQkIRCtxgaDySTp2Pqu8IQHOT2MA==",
                            Phone = "5720935"
                        },
                        new
                        {
                            IdClient = 3,
                            Email = "Jack@Daniels.com",
                            FirstName = "Jack",
                            LastName = "Daniels",
                            Login = "bourbon",
                            Password = "jMmKpRFuPyG8UVQHgW+cEGkeQ3ZtpsCMv5AsJqr8odAyCd5e4ZlgSi659UaV84JkshSOUByolpGws8wbyH02lN3ncNg+tMwkcN2CZS/+yNmp7eSgRjrK/8MJHR2a5s1+ua8NHdVaIKnStGCNwicRtpmijD33iqlg5rnYFJFANyZ6PSJ/ebfeo3ZyZxJR+o9AzEm5GLuKhDleCLDZ4XjAl56e7kOr2h6vIOv7XShSlroBlkU2dRrCG4hQU+Mbk0RYGr1J9LlCOYj2QSR2+C7d7s70fe6NHbX2NLIjHs9WerzcX7xiSjPQfU0XYtqulIr0srUUbGYlHtds1m4iGoy2QQ==",
                            Phone = "1234567878"
                        });
                });

            modelBuilder.Entity("AdvertAPI.Models.Banner", b =>
                {
                    b.HasOne("AdvertAPI.Models.Campaign", "Campaign")
                        .WithMany("Banner")
                        .HasForeignKey("IdCampaign")
                        .HasConstraintName("Campaign_Banner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvertAPI.Models.Campaign", b =>
                {
                    b.HasOne("AdvertAPI.Models.Building", "FromBuilding")
                        .WithMany("CampaignFrom")
                        .HasForeignKey("FromIdBuilding")
                        .HasConstraintName("FromBuilding_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AdvertAPI.Models.Client", "Client")
                        .WithMany("Campaign")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("Client_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AdvertAPI.Models.Building", "ToBuilding")
                        .WithMany("CampaignTo")
                        .HasForeignKey("ToIdBuilding")
                        .HasConstraintName("ToBuilding_Campaign")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
